### ISSUE TITLE
Sign hash verification fails - unable to complete purchase

### ISSUE THREAD

**Issue by pszalko** [tpay-com/omnipay-tpay#3]
I have found the issue with `sign` hash verification when trying to complete `securesale` payment with 3D Secure card.

After 3D Secure card authorization TPay sends request to our `notification url` defined in TPay system.

The problem is `\Omnipay\Tpay\_class_tpay\Notifications\CardNotificationHandler::handleNotification()` reads `sign` param directly from `$_POST` array, therefore it is not possible to pass own signature hash to `\Omnipay\Tpay\TpayGateway::completePurchase()` method.

For the other hand, `$_POST` data send from TPay servers contains `currency` in numeric format, and `amount` as string without decimals.

When creating `\Omnipay\Tpay\Message\CompletePurchaseRequest` class it is required to pass  currency as string ISO code and amount either as float or string with decimals.

Changing params to other than `$_POST` params and passing it to `\Omnipay\Tpay\TpayGateway::completePurchase($purchaseParams)` requires new `sign` hash calculation.

Since `sign` hash is read directly from `$_POST` and ignored when  `sign` param passed in `$purchaseParams`, it is impossible to create and send `CompletePurchaseRequest`.

Correct me if I'm wrong, but it is not clear from the documentation and code, how to make successful complete purchase request.

**Comment by piotrjozwiak** [comment]
There is no need to pass your own sign because our library calculates it automatically.
Please note, you have to use completePurchase method only for 3DS protected payments when Tpay server sends a notification to your endpoint.
We have fixed bad casting of amount by this commit b2eb95395a2bc503f907cd965f378ad469277cca 
To run completePurchase method properly you should follow this example:
`    $completePurchaseResponse = $gateway->completePurchase(array())
        ->setAmount(10.00)
        ->setCurrency('PLN')
        ->setOrderId(32145)
        ->getData();
    var_dump($completePurchaseResponse);`
Where $gateway is Tpay gateway initialized with your access data.

**Comment by pszalko** [comment]
Thank you for fixing the issue.

Your code sample does not have the `$gateway->completePurchase()->send()` action. Do we need to call `send()` on the complete purchase request?

**Comment by piotrjozwiak** [comment]
There is no need to call `send()` action because, in fact, completePurchase does not work as a new request but like a response to the request from Tpay server.

**Comment by pszalko** [comment]
Thanks!
